---
method: AdaBoostClassifier
params:
  n_estimators: 200
  learning_rate: 0.1
  algorithm: SAMME
  random_state: 42
validationcurve:
- param_name: n_estimators
  param_range:
  - 10
  - 60
  - 100
  - 200
  - 600
  - 1000
  - 2000
- param_name: learning_rate
  param_range:
  - 0.1
  - 0.3
  - 0.5
  - 0.7
  - 1
- param_name: algorithm
  param_range:
  - SAMME
  - SAMME.R
rfe: 'True'
datafraction:
    start: 0.3
    stop: 1.0
    num: 10

