---
method: LightGBM
params:
  n_estimators: 500
  max_depth: 6
  learning_rate: 0.5
  subsample: 0.5
  min_child_weight: 5
  boosting_type: dart
  seed: 42
  objective: multiclass
validationcurve:
- param_name: n_estimators
  param_range:
  - 10
  - 60
  - 100
  - 200
  - 600
  - 1000
  - 2000
- param_name: max_depth
  param_range:
  - 1
  - 2
  - 5
  - 10
  - 15
  - 20
  - 25
  - 30
- param_name: learning_rate
  param_range:
  - 0.001
  - 0.01
  - 0.1
  - 0.2
  - 0.3
  - 0.5
  - 0.7
  - 0.8
  - 0.9
- param_name: subsample
  param_range:
  - 0.1
  - 0.2
  - 0.3
  - 0.5
  - 0.7
  - 1.0
- param_name: min_child_weight
  param_range:
  - 1
  - 2
  - 3
  - 5
  - 7
  - 10
- param_name: boosting_type
  param_range:
  - gbdt
  - dart
  - goss
rfe: 'True'
datafraction:
    start: 0.3
    stop: 1.0
    num: 10

